language: php
sudo: required
dist: trusty

php:
  - 7.1.3


env:
  global:
    - setup=basic
    - APP_ENV=local
    - APP_DEBUG=true
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync
    - DB_DATABASE=database/database.sqlite
    - DB_FOREIGN_KEYS=true

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan serve

script:
  - vendor/bin/phpunit
