language: php

php:
  - 7.1.3
  - 7.1.0


before_script:
  - cp .env.testing .env
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit
