### index request
GET http://localhost:8000/api/products/stock
Content-Type: application/json


### store request
POST http://localhost:8000/api/products/stock
Content-Type: application/json

{
  "name" : "Apple Store",
  "price" : 200
}

### show request
GET http://localhost:8000/api/products/stock/1
Content-Type: application/json


### update request
PUT http://localhost:8000/api/products/stock/1
Content-Type: application/json

{
  "name" : "Apple Updated",
  "price" : 200
}

### delete request
DELETE http://localhost:8000/api/products/stock/1
Content-Type: application/json



### ............... Optional Request
GET http://localhost:8000/api/products/stock/get-db-info
Content-Type: application/json

###
GET http://localhost:8000/api/products/stock/accept-by-id/1
Content-Type: application/json

###