
### create new user through api request
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "Sadhan",
  "email": "sadhan@laravel.com",
  "password": "sadhan123456",
  "password_confirmation": "sadhan123456"
}

### login user using credential through api request
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "sadhan@laravel.com",
  "password": "sadhan123456"
}


### request for access resource
GET http://localhost:8000/api/user
Content-Type: application/json
Authorization: Bearer it6rttbAcnKylJKG0Gvvl0bVSZ1vXsY2xZjLgkAcUDeQIZL4oUJlOVPTvpJs


### getResources using token through api request
GET http://localhost:8000/api/getResources
Content-Type: application/json
Authorization: Bearer i0KGZm3E9520aaiB1puGGvxPa89LmeYu5SFadybVuwtGqUbLL53hvtZiYul0


### logout using token through api request
POST http://localhost:8000/api/logout
Content-Type: application/json
Authorization: Bearer it6rttbAcnKylJKG0Gvvl0bVSZ1vXsY2xZjLgkAcUDeQIZL4oUJlOVPTvpJs
###

